src/Entity/Contacto.php
<?php

namespace App\Entity;

use App\Repository\ContactoRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ContactoRepository::class)]
class Contacto
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $Nombre = null;

    #[ORM\Column(length: 255)]
    private ?string $Correo = null;

    #[ORM\Column(length: 2000)]
    private ?string $Mensaje = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): static
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getCorreo(): ?string
    {
        return $this->Correo;
    }

    public function setCorreo(string $Correo): static
    {
        $this->Correo = $Correo;

        return $this;
    }

    public function getMensaje(): ?string
    {
        return $this->Mensaje;
    }

    public function setMensaje(string $Mensaje): static
    {
        $this->Mensaje = $Mensaje;

        return $this;
    }
}

templates/funciones/verificarID.html.twig
<!doctype html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Casino Royal</title>

    <link rel="shortcut icon" href="../../assets/images/fav.png" type="image/x-icon">
    <link rel="stylesheet" href="../../assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../assets/css/fontawesome.min.css">
    <link rel="stylesheet" href="../../assets/css/jquery-ui.css">
    <link rel="stylesheet" href="../../assets/css/plugin/nice-select.css">
    <link rel="stylesheet" href="../../assets/css/plugin/magnific-popup.css">
    <link rel="stylesheet" href="../../assets/css/plugin/slick.css">
    <link rel="stylesheet" href="../../assets/css/plugin/odometer.css">
    <link rel="stylesheet" href="../../assets/css/arafat-font.css">
    <link rel="stylesheet" href="../../assets/css/plugin/animate.css">
    <link rel="stylesheet" href="../../assets/css/style.css">
</head>

<body>
    <!-- start preloader -->
    <div class="preloader align-items-center justify-content-center">
        <div class="load">
            <hr/><hr/><hr/><hr/>
        </div>
    </div>
    <!-- end preloader -->

    <!-- Scroll To Top Start-->
    <button class="scrollToTop"><i class="fas fa-angle-double-up"></i></button>
    <!-- Scroll To Top End -->

      {% include 'partials/menu.html.twig' %}

    <!-- inner banner start -->
    <section class="banner-section inner-banner about">
        <div class="banner-content position-relative d-flex align-items-center">
            <div class="container">
                <div class="row d-flex justify-content-start">
                    <div class="col-sm-7">
                        <div class="text-area">
                            <h2>Casino Royal</h2>
                            <div class="breadcrumb-area">
                                <nav aria-label="breadcrumb">
                                    <ol class="breadcrumb d-flex gap-2 gap-lg-0 mt-2 mt-lg-0">
                                        <li class="breadcrumb-item"><a href="index.html">Inicio</a></li>
                                        <li class="breadcrumb-item"><a href="javascript:void(0)">Perfil</a></li>
                                        <li class="breadcrumb-item active" aria-current="page">Verificación de identidad</li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-5">
                        <div class="illus-area d-none d-sm-block position-absolute bottom-0">
                            <img src="assets/images/banner-careers-illus.png" class="wow fadeInUp" alt="icon">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- banner-section end -->

    <!-- Current Openings start -->
    <section class="current-openings">
        <div class="overlay pt-120 pb-120">
            <div class="container">
                <div class="row cus-mar">
                    <div class="col-lg-5">
                        <div class="section-text">
                            <h5 class="mb-4">¡Verifica tu identidad!</h5>
                            <p>Para poder usar nuestro casino primero debes verificar tu identidad. Recuerda que debe coincidir con los datos proporcionados al registrarte.</p>
                            <br><p>{{usuario.nombre}} {{usuario.apellidos}} - Nacimiento: {{usuario.fechaNacimiento|date('d-m-Y')}}</p></div>
                        
                    </div>
                    <div class="col-lg-6">
                        <div class="tab-content">
                            <div class="tab-pane fade show active" id="all-jobs" role="tabpanel"
                                aria-labelledby="all-jobs-tab">
                                
                                {% if usuario.estaVerificado == 1 %}
                                <div class="single-box d-flex align-items-center justify-content-between">
                                    <div class="text-box">
                                        
                                        <h5 class="mb-2">Identidad verificada</h5>
                                        <ul>
                                            <li>¡Puede retirar hasta 20.000 EUR al día!</li>
                                        </ul>
                                        <span class="lgtxt mt-4">Ya puedes usar nuestro casino.</span>
                                    </div>
                                </div>
                                {% else %}
                                <div class="single-box d-flex align-items-center justify-content-between">
                                    <div class="text-box">
                                        
                                        <h5 class="mb-2">Verifica tu identidad</h5>
                                        <ul>
                                            <li>DNI, carnet de conducir o pasaporte</li>
                                            <li>Selfie</li>
                                        </ul>
                                        <span class="lgtxt mt-4">Tiempo estimado: 3 a 7 minutos.</span>
                                    </div>
                                    <div class="btn-box">
                                        <a href="../verificar/{{usuario.id}}">
                                            <i class="icon-c-arrow-single"></i>
                                        </a>
                                    </div>
                                </div>
                                {{ form(formulario) }}
                                {% endif %}
                                
                            
                        
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Current Openings end -->

   {% include 'partials/footer.html.twig' %}

    <!--==================================================================-->
    <script src="../../assets/js/jquery.min.js"></script>
    <script src="../../assets/js/jquery-ui.js"></script>
    <script src="../../assets/js/bootstrap.min.js"></script>
    <script src="../../assets/js/plugin/jquery.downCount.js"></script>
    <script src="../../assets/js/plugin/slick.js"></script>
    <script src="../../assets/js/plugin/jquery.nice-select.min.js"></script>
    <script src="../../assets/js/plugin/waypoint.min.js"></script>
    <script src="../../assets/js/plugin/jquery.magnific-popup.min.js"></script>
    <script src="../../assets/js/plugin/wow.min.js"></script>
    <script src="../../assets/js/plugin/odometer.min.js"></script>
    <script src="../../assets/js/plugin/viewport.jquery.js"></script>
    <script src="../../assets/js/plugin/plugin.js"></script>
    <script src="../../assets/js/main.js"></script>
</body>

</html>